version: '2'

services:
  memcached:
    image: bitnami/memcached
    ports:
      - '11211:11211'
    environment:
      - MEMCACHED_USERNAME=my_user
      - MEMCACHED_PASSWORD=my_password
      - MEMCACHED_CACHE_SIZE=4096
      - MEMCACHED_MAX_CONNECTIONS=10240
