---
version: '2.2'

services:
  prometheus:
    image: prom/prometheus:v2.20.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - './prometheus.yaml:/etc/prometheus/prometheus.yml'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
      - '--storage.tsdb.retention.time=90d'
      - '--web.external-url=http://127.0.0.1:9090'
  pushgateway:
    image: prom/pushgateway:v1.4.1
    container_name: pushgateway
    restart: always
    ports:
      - "9091:9091"
    volumes:
      - './pushgateway.yaml:/etc/pushgateway/pushgateway.yaml'
    command:
      - '--web.config.file=/etc/pushgateway/pushgateway.yaml'
      - '--push.disable-consistency-check'
  blackbox-exporter:
    image: prom/blackbox-exporter:v0.21.0
    container_name: blackbox_exporter
    ports:
      - "9115:9115"
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
      - '--web.listen-address=0.0.0.0:9100'
      - '--web.config=/etc/prometheus/config.yaml'
    # network_mode: host
    pid: host
    ports:
      - "9100:9100"
    restart: unless-stopped
    volumes:
      - './node_exporter.yaml:/etc/prometheus/config.yaml'
      # - '/:/host:ro,rslave'