version: '3.3'

services:
  rabbitmq:
    image: rabbitmq:3.8.28-management-alpine
    ports:
      - '15672:15672'
      - '5672:5672'
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root123456